name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: rickragav/sirenuix-nextjs  # Use the latest version available

      with:
        dockerfile: Dockerfile  # Specify the path to your Dockerfile if it's not in the root directory

    - name: Build Docker Image
      run: docker build -t my-docker-image .

    # - name: Login to Docker Hub (optional)
    #   if: secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != ''
    #   run: |
    #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    # - name: Push Docker Image to Docker Hub (optional)
    #   if: secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != ''
    #   run: docker push my-docker-image
