name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sirenuix/nextjs-ui:$(date +%s)

    - name: Login to Docker Hub
      run: |
        echo sirenuix | docker login -u sirenuix -p Apple@041622

    - name: Push Docker Image to Docker Hub
      run: docker push sirenuix/nextjs-ui:$(date +%s)
